### ISSUE TITLE
Question Roundcube

### ISSUE THREAD

**Issue by Technikte** [patschi/mailpiler-mailcow-integration#2]
Hello,
since I haven't found a better way to contact you here I will write to you.
Is there any chance that you can port or create a similar plugin for roundcube while using a mailcow server in the background.
It seems that you are active on the mailpiler project, so I dont know if you anyhow willing to code for a "competitor" webmailer.
A litte bit of funding I could send you, maybe if there is a chance you can send me a short message about needed money or so.

Thanks in advance for your time.

**Comment by patschi** [comment]
Hi,

this issue is quite off-topic for piler-mailcow-integration.

I don't see why or how such an integration would be ever need for a webmail interface like Roundcube. Roundcube allows to use IMAP/SMTP as authentication, so I think that's pretty much all you need for a classic webmail.

Also Roundcube is not a "competitor" to piler, because piler is not a webmail - it's an email archiving solution.

I'm not looking for programming tasks, so I'm closing this issue.

**Comment by Technikte** [comment]
Yeah, it is really off-topic, yes.
Well, I thought an inegration could be used in the webmailer to create alias and so right in the webinterface.

Alright, I have had only a quick look at mailpiler and it seemed like a webmailer software.
Thanks any way ! 
Stay safe.
